<?php
use Drupal\Core\Entity\ContentEntityType;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\field\Entity\FieldConfig;
use Drupal\Core\Entity\Entity\EntityFormDisplay;
use Drupal\Core\Entity\Entity\EntityViewDisplay;
/**
 * @file
 * Primary module hooks for Client URL module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */


function client_url_install($is_syncing) {
    $entity_type_definations = \Drupal::entityTypeManager()->getDefinitions();
    $file = file('modules/custom/client_url/source/domain.txt', FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
    foreach($file as $value) {
      $domain[] = ['url' => $value];
    }
    /* @var $definition EntityTypeInterface */
    foreach ($entity_type_definations as $definition) {
      if ($definition instanceof ContentEntityType) {
        $content_entity_id = $definition->id();
        $bundle = \Drupal::service('entity_type.bundle.info')->getBundleInfo($content_entity_id);
        FieldStorageConfig::create(array(
            'field_name' => 'urls',
            'entity_type' => $content_entity_id, 
            'type' => 'client_url',
            'cardinality' => count($file),
            ))->save();
        foreach($bundle as $key => $values) {
            FieldConfig::create([
                'field_name' => 'urls',
                'entity_type' => $content_entity_id,
                'bundle' => $key, // content type
                'label' => 'Url field',
                'default_value' => $domain
                ])->save();
            // Manage form display
            $form_display = \Drupal::service('entity_display.repository')->getFormDisplay($content_entity_id, $key );
            $form_display = $form_display->setComponent('urls', ['type' => 'text_textfield','default_value' => ['abc','abc','abc','abc','abc','abc']]);
            $form_display->save();
            // Manage view display
            $view_display = \Drupal::service('entity_display.repository')->getViewDisplay($content_entity_id, $key);
            $view_display->setComponent('urls', ['type' => 'text_default']);
            $view_display->save();
        }
      }
    }
}